### ISSUE TITLE
add external Ollama IP connection

### ISSUE THREAD

**Issue by coolrazor007** [your-papa/obsidian-Smart2Brain#110]
### Feature Area

Settings

### Painpoint

I was able to setup Ollama on my local server (separate from my laptop) and even added it in settings successfully.  However, I can't setup the "setup" spot to point the "Run on your machine" to my server's IP.  Can we add a feature to allow the IP that was successfully added earlier?

![smart_to_brain_settings](https://github.com/your-papa/obsidian-Smart2Brain/assets/62222426/21fc736a-eff4-4b2f-920e-7e9a3e13e96e)
![smart_to_brain_setup](https://github.com/your-papa/obsidian-Smart2Brain/assets/62222426/ca352565-7257-48ec-97db-b32417428c2b)

### Describe your idea

I want to use Ollama on my network

**Comment by nicobrauchtgit** [comment]
This should work it more seems like to me that the origins are not set on the ollama instance on your server. Are you running the ollama docker image?

**Comment by coolrazor007** [comment]
> This should work it more seems like to me that the origins are not set on the ollama instance on your server. Are you running the ollama docker image?

I am running Ollama in a docker image and can hit it from my laptop on the same IP and PORT using other tools.

Do I need to do something regarding "origins" or CORS on the Ollama side?

**Comment by Leo310** [comment]
Yes, take a look at https://github.com/your-papa/obsidian-Smart2Brain/issues/71. You need to set the OLLAMA_ORIGINS environment variable on your remote server before running Ollama.

**Comment by nicobrauchtgit** [comment]
To add the origins evn var add this to your docker run command:  `-e OLLAMA_ORIGINS='app://obsidian.md*'`

**Comment by coolrazor007** [comment]
You guys were right!  I was setting the env var in .bashrc and /etc/environment to no avail.  But this worked:
`docker run -d -v /local/models/textgen:/root/.ollama -e OLLAMA_ORIGINS='app://obsidian.md*' -p 11434:11434 --name ollama-4-obsidian ollama/ollama`

Obviously that is a little specific to my setup but there you go for the next person!
