### ISSUE TITLE
Ollama Windows Origins ont set correctly

### ISSUE THREAD

**Issue by flowingblaze** [your-papa/obsidian-Smart2Brain#123]
### What happened?

For whatever reason I cannot get the origins set correctly?
![image](https://github.com/your-papa/obsidian-Smart2Brain/assets/107226733/d315860a-b771-47a2-bee9-2cf9e165edec)
im on windows 10
![image](https://github.com/your-papa/obsidian-Smart2Brain/assets/107226733/c5807851-3dd6-441b-beff-68319896561c)

### Steps to Reproduce

1. follow steps in the first screenshot 
2. do the command said in the screenshot
3. do the command said by Ollama 

### Smart Second Brain Version

1.2.0

### Debug Info

SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.4.16
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 35
	Plugins enabled: 32
		1: TimeStamper v1.3.0
		2: AutoMOC v1.4.0
		3: Recent Files v1.3.8
		4: Settings Search v1.3.10
		5: Commander v0.5.1
		6: Vault Changelog v0.1.0
		7: Note Refactor v1.8.2
		8: Periodic Notes v0.0.17
		9: Omnivore v1.10.2
		10: Reflection v1.0.1
		11: Media DB Plugin v0.6.0
		12: Daily Activity v0.4.0
		13: Longform v2.0.7
		14: Typing speed v1.2.1
		15: Folder Index v1.0.24
		16: Importer v1.5.6
		17: Journal Review v2.3.2
		18: Better Word Count v0.10.0
		19: Typewriter Scroll v0.2.2
		20: Dataview v0.5.66
		21: Buttons v0.5.1
		22: Beautitab v1.6.1
		23: Paste URL into selection v1.7.0
		24: Templater v2.2.4
		25: Heatmap Calendar v0.6.0
		26: Footnote Shortcut v0.1.3
		27: ActivityWatch v1.3.0
		28: LanguageTool Integration v0.3.7
		29: Wikipedia v1.0.3
		30: Smart Typography v1.0.18
		31: Emoji Toolbar v0.4.1
		32: Smart Second Brain v1.2.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by b0b-103** [comment]
Go to windows search and search "environmental variables"

Then Click on "Environmental Variables" > "New"


For Variable Name put: 
OLLAMA_ORIGINS

For Variable Value put:
"app://obsidian.md*"

![image](https://github.com/your-papa/obsidian-Smart2Brain/assets/111203155/0d7a13f6-2a82-404b-a07b-6521ad6aa478)

**Comment by flowingblaze** [comment]
Thank you for your help! It is indexing as I write this, I will post a new issue if I have a different error. Thanks!
