### ISSUE TITLE
Unable to change similarity

### ISSUE THREAD

**Issue by t-if** [your-papa/obsidian-Smart2Brain#131]
### What happened?

I cannot drag the slider that changes the similarity level. The creativity works fine, though.

### Error Statement

N/A

### Steps to Reproduce

1. Start Smart Second Brain
2. Try to move the similarity slider

### Smart Second Brain Version

1.3.0

### Debug Info

SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.12
	Operating system: Windows 10 Home 10.0.22621
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.5.4
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 62
	Plugins enabled: 61
		1: Waypoint v2.1.0
		2: Underline v1.3.0
		3: Toggle Case v1.1.0
		4: Todoist Sync v1.13.0
		5: Timer v1.0.7
		6: Text Extractor v0.5.1
		7: Tag Wrangler v0.6.1
		8: Table of Contents v0.2.0
		9: Surfing v0.9.11
		10: Advanced Tables v0.21.0
		11: Better Word Count v0.10.1
		12: Buttons v0.5.1
		13: Calendar v1.5.10
		14: Charts v3.9.0
		15: Color Palette v2.5.1
		16: Commander v0.5.1
		17: Contribution Graph v0.9.0
		18: DataLoom v8.16.0
		19: Dataview v0.5.66
		20: Day and Night v1.2.1
		21: Day Planner v0.20.4
		22: Editor Syntax Highlight v0.1.3
		23: Editing Toolbar v2.4.16
		24: Emoji Shortcodes v2.2.0
		25: Excalidraw v2.1.8
		26: File Hider v1.1.1
		27: File Tree Alternative v2.5.7
		28: Hover Editor v0.11.20
		29: Homepage v3.8.0
		30: Home tab v1.2.0
		31: Folder Note v0.7.3
		32: Folders to Graph v1.0.0
		33: Hider v1.3.1
		34: Iconize v2.12.0
		35: Kanban v1.5.3
		36: Ledger v0.3.2
		37: List Callouts v1.2.7
		38: Markdown Formatting Assistant v0.4.1
		39: Mathpad v0.8.14
		40: MetaEdit v1.8.2
		41: Minimal Theme Settings v7.5.0
		42: Quick Explorer v0.2.8
		43: Plugin Update Tracker v1.5.2
		44: Periodic Notes v0.0.17
		45: Paste URL into selection v1.7.0
		46: PDF Highlights v0.0.4
		47: Party🎉 v2.1.0
		48: Omnisearch v1.22.2
		49: Multi-Column Markdown v0.9.1
		50: QuickAdd v1.8.1
		51: Settings Search v1.3.10
		52: Style Settings v1.0.8
		53: Smart Typography v1.0.18
		54: Hotkeys for templates v1.4.3
		55: Chronology v1.1.11
		56: OpenWeather v1.7.1
		57: Citations v0.4.5
		58: Reminder v1.1.15
		59: Share my plugin list v0.3.3
		60: Digital Garden v2.56.2
		61: Smart Second Brain v1.3.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by rasulovk** [comment]
Hi, I have same issue, I tried all recommendations but still couldn't change similarity. One thing is I'm using Ollama server remotely, does it makes difference ?  My obsidian version is  v1.6.7, use default theme and have few community plugins. Could you please advise what could be cause?
