### ISSUE TITLE
How to make it work with a remote ollama server

### ISSUE THREAD

**Issue by jtencioc101** [your-papa/obsidian-Smart2Brain#138]
### Feature Area

Settings

### Painpoint

I am trying to connect the plugin with a self hosted ollama server in my local network, meaning I am not running ollama locally

### Describe your idea

I want to know if there is a ny chance to configure the plugin to work with a remote ollama server.
It seems the intial set uo is able to connecto to my server and see the models I have intalled
![image](https://github.com/your-papa/obsidian-Smart2Brain/assets/51888085/c85cfdf3-d1a0-403c-936b-c71766eb9eff)

However, I am stuck in this part of the setup, maybe I am missing something here.
![image](https://github.com/your-papa/obsidian-Smart2Brain/assets/51888085/76f0e7d7-7e6a-4c83-a996-30c696eba090)

**Comment by Leo310** [comment]
It should be able to connect to the remote instance. Are you sure you set the correct OLLAMA_ORIGINS environment variable?

**Comment by jsrdcht** [comment]
It works with cloudflare hosted ollama serve, I have tried.

**Comment by jtencioc101** [comment]
> It should be able to connect to the remote instance. Are you sure you have set the correct OLLAMA_ORIGINS environment variable?

After double cheking I found I had the wrong IP, it's working now.
Thank you!
