### ISSUE TITLE
Support all models

### ISSUE THREAD

**Issue by MiracleXYZ** [your-papa/obsidian-Smart2Brain#18]
I tried to set the Ollama chat model and embed model to different values, but most of the time I got these error messages once I hit "Initialize":

<img width="537" alt="image" src="https://github.com/your-papa/obsidian-Smart2Brain/assets/30370926/ef0e7944-db28-439e-bc8c-516887504390">

It works fine when I set both models to `llama2` or `mistral`. But when I change to some different models (or even the same model with a different tag like `llama2:13b`), the plugin just says they're "invalid".

**Comment by Leo310** [comment]
This will be fixed in a future version. We currently hard code the supported models in the [papa-ts](https://github.com/your-papa/papa-ts) and throw an error if an unsupported model is selected.
