### ISSUE TITLE
Bug: Needs internet in offline mode

### ISSUE THREAD

**Issue by slonoed** [your-papa/obsidian-Smart2Brain#19]
I tried to use extension but it doesn't work in offline. There are multiple errors in console like these

```
GET https://tiktoken.pages.dev/js/gpt2.json net::ERR_INVALID_HANDLE
```

```
VM315:1     Uncaught (in promise) TypeError: Failed to fetch
    at eval (eval at <anonymous> (plugin:smart-second-brain:1:1), <anonymous>:1:1)
    at eval (plugin:smart-second-brain:230:20919)
    at onFailedAttempt (plugin:smart-second-brain:230:20525)
    at r.eval [as _fn] (plugin:smart-second-brain:230:9961)
    at eval (plugin:smart-second-brain:230:7118)
```

```
plugin:smart-second-brain:243 Failed to calculate number of tokens, falling back to approximate count TypeError: Failed to fetch
    at eval (plugin:smart-second-brain:230:20919)
    at onFailedAttempt (plugin:smart-second-brain:230:20525)
    at r.eval [as _fn] (plugin:smart-second-brain:230:9961)
    at eval (plugin:smart-second-brain:230:7118)
```

They caused by one of "langchain" dependencies.

And "langchain" itself is included into "papa-ts" dependency. 
"papa-ts" is not included into "package.json" but it's added on build step right before publishing to NPM
https://github.com/your-papa/obsidian-Smart2Brain/blob/main/.github/workflows/release.yml#L23

Npm page https://www.npmjs.com/package/papa-ts shows link to repo https://github.com/your-papa/papa-ts
However, git repo is unavailable.

When I look at "papa-ts" source code I don't see anything suspicious, but I was alarmed when "offline" mode plugin tried to reach out internet. I think there should be clear explanation to README.

UPD. In addition this may violate Obsidian policies https://docs.obsidian.md/Developer+policies
- Obfuscate code to hide its purpose.
- The following are only allowed if clearly indicated in your README: 
   - Close sourced code. This will be handled on a case by case basis.
   - Network use. Clearly explain which remote services are used and why they're needed.

**Comment by Leo310** [comment]
We just open-sourced the [papa-ts](https://github.com/your-papa/papa-ts) dependency.
The offline issue still needs to be investigated.
