### ISSUE TITLE
Cannot install - Request Failed 404

### ISSUE THREAD

**Issue by replete** [your-papa/obsidian-Smart2Brain#31]
MacOS 13.6.4
Obsidian 1.5.8

![Screenshot 2024-02-28 at 17 45 43](https://github.com/your-papa/obsidian-Smart2Brain/assets/812139/387ce986-2f6c-45c6-9d64-755170e47498)

Not sure if this an obsidian community plugin issue, but I can't seem to install this particular plugin.

**Comment by Leo310** [comment]
Please retry installing it. Should work now

**Comment by replete** [comment]
Sorted. Cheers Leo, keep up the good work!

**Comment by replete** [comment]
@Leo310 Does this plugin actually do anything? I cannot see any commands or panels..
