### ISSUE TITLE
Local models are taking ton of space and I think it should be stated in docs

### ISSUE THREAD

**Issue by prwnr** [your-papa/obsidian-Smart2Brain#43]
Not necessarily a true plugin issue, but Im not sure of other way to point this out.

I started using the plugin few days ago with local LLM (Ollama) and I think that it must be stated somewhere in the docs that using a local LLM is going to build up a big `.bin` file in the plugin directory (maybe it does that for online LLMs too, I cant tell)

But that big local file in combination with Obsidian Sync is going to end up cluttering the Sync history (because this `.bin` file changes periodically and Sync is going to store every revision of this file). 

The only way to avoid that is to put in the `.obsidian/plugins/smart-second-brain` directory as excluded from the Sync service.

I know that this happens, because I ended up getting 2GB of my Sync service eaten in a day by your plugin, not knowing this, and the only way to get that space back was to re-create whole vault. 

So, that's why I think it would be worth to note this in documentation for people who are going to use this plugin and have Sync (or even other sync service) in use with limited space.

**Comment by xc0f0c0bx** [comment]
Why bot utilizing couchdb?

**Comment by nicobrauchtgit** [comment]
Hi @prwnr, the bin file is the vector store for the vault and thus essential for the plugin. Our current hot fix is to put those files in a separate folder so it can be excluded on its own. However we would like to find a better solution, if possible. Could you tell me how big that file is in your case?

**Comment by prwnr** [comment]
@nicobrauchtgit, currently it sits at 92mb - so, for the file itself it's not that big, it's the matter of it being often reindexed, where sync stores each version as individual one in history and ends up cluttering the space.

**Comment by nicobrauchtgit** [comment]
Okay so updating the bin less often might help. But maybe there is a more elegant solution natively from obsidian, i'll have to check
