### ISSUE TITLE
Add fallback if vault language is not supported yet

### ISSUE THREAD

**Issue by nicobrauchtgit** [your-papa/obsidian-Smart2Brain#46]
Not sure if it relates to this issue. Crash at `initialAssistantMessage: la[window.localStorage.getItem("language") || "en"].initialAssistantMessage`
```
Plugin failure: smart-second-brain TypeError: Cannot read properties of undefined (reading 'initialAssistantMessage')
    at anonymous (plugin:smart-second-brain:467:3792)
    at e.<anonymous> (app.js:1:2046123)
    at app.js:1:237544
    at Object.next (app.js:1:237649)
    at a (app.js:1:236367)
```

_Originally posted by @SettingDust in https://github.com/your-papa/obsidian-Smart2Brain/issues/11#issuecomment-1987194159_

**Comment by SettingDust** [comment]
Chinese
