### ISSUE TITLE
CORS policy error on first install

### ISSUE THREAD

**Issue by tagalag** [your-papa/obsidian-Smart2Brain#62]
### What happened?

Trying to run the plugin with gemma and nomic-embed-text.

![image](https://github.com/your-papa/obsidian-Smart2Brain/assets/96966238/6180f867-7142-4fa9-85d2-c9951c4e4e20)

I have tried defining the OLLAMA_ORIGINS variable in the ollama.service file but that didn't work. 
Ollama is starting as a system service on boot and the plugin when obsidian is started.

I've tried running the ollama service with `ollama serve` but then it doesn't see any of my installed models.

Running Obsidian 1.5.11 on Debian 12 (bookworm)

### Error Statement

![Obsidian_error](https://github.com/your-papa/obsidian-Smart2Brain/assets/96966238/6e141862-fb55-488a-b97f-240337f5fa36)

### Smart Second Brain Version

0.6.0

### Debug Info

SYSTEM INFO:
	Obsidian version: v1.5.11
	Installer version: v1.5.3
	Operating system: #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) 6.1.0-18-amd64
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Atom v0.0.0
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 24
	Plugins enabled: 17
		1: Annotator v0.2.11
		2: Dictionary v2.22.0
		3: Dynamic Table of Contents v0.0.27
		4: File Tree Alternative v2.5.2
		5: Indentation Lines v1.0.1
		6: WordNet Dictionary v2.0.3
		7: Templater v2.2.3
		8: Iconize v2.11.0
		9: Paste URL into selection v1.7.0
		10: Style Settings v1.0.8
		11: Advanced Codeblock v1.1.5
		12: Diagrams v1.5.0
		13: Markdown Formatting Assistant v0.4.1
		14: PlantUML v1.7.0
		15: Hard Breaks v0.1.1
		16: Git v2.24.1
		17: Smart Second Brain v0.6.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by Leo310** [comment]
Can you confirm that running

```bash
OLLAMA_ORIGINS="*" ollama serve
```

is also throwing the CORS policy error

**Comment by tagalag** [comment]
Running that manually worked but when adding it to the service file in ExecStart the ollama service doesn't start. I'm trying to make ollama accept the connection automatically instead of having to set the variable and run ollama myself every time I want to use the plugin.
![image](https://github.com/your-papa/obsidian-Smart2Brain/assets/96966238/904618c8-4a56-4ac3-8f03-8141b47d226b)
![image](https://github.com/your-papa/obsidian-Smart2Brain/assets/96966238/b445cf98-fb28-4027-a969-af488ce2ecd0)
Also I set OLLAMA_ORIGINS and started ollama as a normal user, not root.

**Comment by Leo310** [comment]
This should be related to this open [ollama issue](https://github.com/ollama/ollama/issues/2335).
Nothing we can do but wait I think. So I am closing this issue for now but feel free to reopen.

**Comment by elketron** [comment]
Hello i stumble accross this and. i got it working
after running systemctl edit ollama.service i added this at the top of the file
```
[Service]
Environment="OLLAMA_ORIGINS=*"
```
then i save and ran ``` sysemctl daemon-reload```
after which i and ``` sudo systemctl restart ollama.service```

this got it working for me in obsidian and i no longer get the cors error
