### ISSUE TITLE
It asks for OpenAI key when you try to run it with ollama.

### ISSUE THREAD

**Issue by hyperphysin** [your-papa/obsidian-Smart2Brain#7]
<img width="850" alt="1" src="https://github.com/nicobrauchtgit/obsidian-Smart2Brain/assets/43456637/0004d6cf-d418-4040-9fe7-bd78c30b02ca">

Incognito Mode is on.
<img width="799" alt="2" src="https://github.com/nicobrauchtgit/obsidian-Smart2Brain/assets/43456637/b71ca77a-ebfc-4409-9f33-ca0994ad57e4">

**Comment by replete** [comment]
![Screenshot 2024-02-22 at 00 12 56](https://github.com/your-papa/obsidian-Smart2Brain/assets/812139/70f89202-2e6f-40ca-a30a-3ad29f8b2cb2)

Same problem, will check back for updates as I'm particularly interested in an ollama obsidian integration. Look forward to trying this out.

**Comment by Leo310** [comment]
Is fixed in next release
