### ISSUE TITLE
Running Locally with Ollama Fails

### ISSUE THREAD

**Issue by luguenth** [your-papa/obsidian-Smart2Brain#71]
### What happened?

Hey, I just tried your Plugin, but I can't get it running with a local LLM. I followed the instructions in your Plugin but on the 6th step "Test if the origins are set correctly" it just shows a red cross "❌".

On the Ollama log there is a 403:
```
➜  ~ $env:OLLAMA_ORIGINS="*"; ollama serve
zsh: command not found: :OLLAMA_ORIGINS=*
time=2024-04-02T14:52:17.234+02:00 level=INFO source=images.go:710 msg="total blobs: 0"
time=2024-04-02T14:52:17.234+02:00 level=INFO source=images.go:717 msg="total unused blobs removed: 0"
time=2024-04-02T14:52:17.234+02:00 level=INFO source=routes.go:1021 msg="Listening on 127.0.0.1:11434 (version 0.1.28)"
time=2024-04-02T14:52:17.234+02:00 level=INFO source=payload_common.go:107 msg="Extracting dynamic libraries..."
time=2024-04-02T14:52:20.266+02:00 level=INFO source=payload_common.go:146 msg="Dynamic LLM libraries [cpu_avx cpu rocm_v6 cpu_avx2 cuda_v11 rocm_v5]"
time=2024-04-02T14:52:20.266+02:00 level=INFO source=gpu.go:94 msg="Detecting GPU type"
time=2024-04-02T14:52:20.266+02:00 level=INFO source=gpu.go:265 msg="Searching for GPU management library libnvidia-ml.so"
time=2024-04-02T14:52:20.269+02:00 level=INFO source=gpu.go:311 msg="Discovered GPU libraries: [/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.550.54.14]"
time=2024-04-02T14:52:20.322+02:00 level=INFO source=gpu.go:323 msg="Unable to load CUDA management library /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.550.54.14: nvml vram init failure: 9"
time=2024-04-02T14:52:20.323+02:00 level=INFO source=gpu.go:265 msg="Searching for GPU management library librocm_smi64.so"
time=2024-04-02T14:52:20.323+02:00 level=INFO source=gpu.go:311 msg="Discovered GPU libraries: []"
time=2024-04-02T14:52:20.323+02:00 level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-04-02T14:52:20.323+02:00 level=INFO source=routes.go:1044 msg="no GPU detected"
[GIN] 2024/04/02 - 14:52:20 | 403 |       28.34µs |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/04/02 - 14:52:20 | 200 |     223.176µs |       127.0.0.1 | GET      "/api/tags"
``` 

Ollama works for me in other Instances. For example in VSCode. Any Ideas what could've gone wrong here?

### Error Statement

```
Access to fetch at 'http://localhost:11434/api/tags' from origin 'app://obsidian.md' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
plugin:smart-second-brain:445 
        
        
GET http://localhost:11434/api/tags net::ERR_FAILED 403 (Forbidden)
```

### Smart Second Brain Version

1.0.0

### Debug Info

SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.11
	Operating system: #202403110203~1710198088~22.04~1a3dbc7 SMP PREEMPT_DYNAMIC Mon M 6.8.0-76060800daily20240311-generic
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 5
	Plugins enabled: 5
		1: Self-hosted LiveSync v0.22.16
		2: Tasks v6.2.0
		3: Iconize v2.11.5
		4: Charts v3.9.0
		5: Smart Second Brain v1.0.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by luguenth** [comment]
Okay this works if you replace: `$env:OLLAMA_ORIGINS="*"; ollama serve` with `OLLAMA_ORIGINS="*" ollama serve` on Ubuntu

**Comment by lyctw** [comment]
I've to type `export OLLAMA_ORIGINS="*" && ollama serve` instead..

**Comment by replete** [comment]
Just a heads up but on MacOS 13, the `launchctl setenv ...` does not work as expected. What did work for me was launching ollama as @luguenth described: `OLLAMA_ORIGINS="*" ollama serve`

**Comment by pressdarling** [comment]
> I've to type `export OLLAMA_ORIGINS="*" && ollama serve` instead..

Making a note since I didn't document how I resolved this issue the first time I ran into it...confirmed this fix works on macOS 14, as @replete mentioned.

Because I'm going to forget that again, I set `ollamas` as an alias (`alias ollamas='export OLLAMA_ORIGINS="*" && ollama serve'`) - there's almost certainly a better way to do this, but it works for me.
