### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by xeor** [your-papa/obsidian-Smart2Brain#81]
### Feature Area

Settings

### Painpoint

Setting OLLAMA_ORIGIN to `*` hurts.. Feels more insecure than what it should be

### Describe your idea

Document to set it to `OLLAMA_ORIGINS='app://obsidian.md*'` instead. It is a comma separated list and should contain more than just a star

### Alternatives

Just leave it as documented, but maybe add some comment?

**Comment by nicobrauchtgit** [comment]
Yeah that is a fair point!
