### ISSUE TITLE
Setup messed up?

### ISSUE THREAD

**Issue by sorin-costea** [your-papa/obsidian-Smart2Brain#84]
There may be a few different understanding problems here so please bear with me:
1. I installed the plugin from Obsidian, then did some settings on the plugin page (to use tinyllm)
2. I restarted Obsidian, I got on the right the S2B initialization steps for Ollama - which suggested me another model. I accepted that one and forgot which. Now I can't see which one anymore because the settings page show still tinyllm (I didn't pay attention, assuming it will be set). So no idea which is now active - the one from settings or the one from initialization.
3. Now when I chat I only get standard answers, nothing from my notes.
4. I later added a PDF to Obsidian, won't be returning answers either.

So, any idea why no answers?
In the meantime I will reinstall the plugin and ollama from scratch, just to see if there's any step I might have messed up.

**Comment by sorin-costea** [comment]
Okay after reinstalling S2B: TypeError, failed to fetch.

**Comment by Leo310** [comment]
The models (embedding + chat model) shown on the plugin settings page should be the ones that are selected. The model shown in the initialization steps is the embedding model used for the Retrieval Augmented Generation (RAG) Pipeline. The model that can be seen in the chat window is the chat model.

When you chat and nothing from your notes is retrieved do you see a notice in the top right that says "No notes retrieved. Maybe lower the similarity threshold."? If yes, you need to lower the Similarity slider to 40% or even lower, depending no the embedding model you use.

PDFs are not supported yet.

**Comment by sorin-costea** [comment]
Indeed, all these points helped along the way. Thank you!
