### ISSUE TITLE
Bug report: Ollama command is not displayed 

### ISSUE THREAD

**Issue by mjohansona2** [your-papa/obsidian-Smart2Brain#89]
### What happened?

When I click on "Open S2B Chat" in obsidian I get the setup but there is no command to paste and the Test button just shows a X. Ollama is running and interacts just fine in cli.

![s2b-setup](https://github.com/your-papa/obsidian-Smart2Brain/assets/6199686/a389e3fd-fd7c-4719-a67c-d6cd079c4247)

### Smart Second Brain Version

1.0.2

### Debug Info

SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.12
	Operating system: #1 SMP PREEMPT_DYNAMIC Kali 6.6.9-1kali1 (2024-01-08) 6.6.9-amd64
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Border v1.2.15
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 29
	Plugins enabled: 21
		1: Calendar v1.5.10
		2: Linkify v1.0.14
		3: Various Complements v9.4.0
		4: Style Settings v1.0.8
		5: Supercharged Links v0.12.1
		6: Crossbow v1.4.0
		7: Folder notes v1.1.8
		8: Templater v2.2.3
		9: Dataview v0.5.66
		10: QuickAdd v1.8.1
		11: Natural Language Dates v0.6.2
		12: Banners v1.3.3
		13: Tracker v1.13.3
		14: List Modified v2.2.3
		15: Page Properties v1.0.3
		16: OpenWeather v1.7.1
		17: Achievements v0.0.10
		18: Tasks v6.2.0
		19: Git v2.24.1
		20: Task Marker v0.5.1
		21: Smart Second Brain v1.0.2

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by nicobrauchtgit** [comment]
Oh that is weird, the command should be displayed there. We'll look into it. In the meantime if you stop your ollama instance and run it with: OLLAMA_ORIGINS="app://obsidian.md*" ollama serve
 
or OLLAMA_ORIGINS="app://obsidian.md*" && ollama serve

it should work

**Comment by mjohansona2** [comment]
The "OLLAMA_ORIGINS="app://obsidian.md*" ollama serve" command worked to get it to start doing the indexing and get me a chat window. Will try the 2nd command later after indexing is all completed and let you know.

**Comment by guillaumemeyer** [comment]
Have exactly the same issue on Ubuntu.

**Comment by dlandry** [comment]
Had the same issue as well and along with starting ollama using:

```
OLLAMA_ORIGINS="app://obsidian.md*" ollama serve
```

to start ollama, I  also had to restart Obsidian.

**Comment by Leo310** [comment]
fixed by https://github.com/your-papa/obsidian-Smart2Brain/issues/117
