### ISSUE TITLE
Doesn't seem to be using my embeddings

### ISSUE THREAD

**Issue by replete** [your-papa/obsidian-Smart2Brain#91]
### What happened?

![Screenshot 2024-04-11 at 22 21 48](https://github.com/your-papa/obsidian-Smart2Brain/assets/812139/2542190c-c474-4f0a-9bbd-7307ba76e907)

First of all, amazing work putting this together. This looks like the best candidate for this scenario. Khoj was a pain and didn't work, other solutions just didn't work. And this one almost works 🤣. Using ollama for this makes the most sense, so good arch decisions.

Unfortunately, it's not working for me, the indexing seemed to work well, but the agent is not aware of my notes. Should isRAG be true? The conversation is entirely self-contained.

### Error Statement

[PAPA] Running RAG... Input: 
{isRAG: false, userQuery: 'What is celticos?', chatHistory: 'Assistant: Hello, I am your assistant. How can I h…What errors did I make recently, from my journal?', lang: 'en'}
chatHistory
: 
"Assistant: Hello, I am your assistant. How can I help you?\nUser: Tell me a joke\nAssistant: Sure! Here's a joke:\nQ: What do you call a fish with no eyes?\nA: A fsh. Get it? F-sh.\nUser: What did I do yesterday?\nAssistant: Based on the chathistory, you asked your assistant for a joke and they told you one. Yesterday, you spoke with them about something else.\nUser: What errors are in my journal for the last few days\nAssistant: Based on your chathistory, it appears that there were no errors recorded in your journal for the past few days.\nUser: Summarise journal\nAssistant: Based on the chathistory, you have been speaking with your assistant about various topics and there were no errors recorded in your journal for the past few days.\nUser: What is in my morning ritual?\nAssistant: Based on the chathistory, you have been speaking with your assistant about various topics and there were no errors recorded in your journal for the past few days. Your morning ritual includes a cup of coffee or tea, a shower, and getting dressed before starting work.\nUser: can you see my notes?\nAssistant: Based on the chathistory, it appears that there were no notes recorded for the past few days. However, if you would like me to send you a copy of your notes, please let me know and I will be happy to assist you with that.\nUser: what did I write yesterday\nAssistant: According to the chathistory, it appears that there were no notes recorded for the past few days. However, if you would like me to send you a copy of your notes, please let me know and I will be happy to assist you with that.\nUser: what did I write yesterday?\nAssistant: Based on the chathistory, it appears that there were no notes recorded for the past few days. However, if you would like me to send you a copy of your notes, please let me know and I will be happy to assist you with that.\nUser: What errors are in my journal?\nAssistant: Failed to run Smart Second Brain (Error: ,Error: Expected a Runnable, function or object.\nInstead got an unsupported type.,). Please retry.\nUser: What errors did I make recently, from my journal?"
isRAG
: 
false
lang
: 
"en"
userQuery
: 
"What is celticos?"

### Steps to Reproduce

> run ollama
> index vault
> chat with agent
> agent does not seem to reference any notes, conversation is self-referential

### Smart Second Brain Version

1.0.2

### Debug Info

Obsidian 1.5.12, macos 13.6.5, ollama 0.1.31

**Comment by nicobrauchtgit** [comment]
This might be bad UI on our part but the solution is easy. Just click on the octopus icon inside the bump. If it has accent color you chat with your notes😊

**Comment by Leo310** [comment]
First, thanks for your extensive feedback. Regarding your first problem:

> I did toggle the button, enabling makes `isRAG: true` but I'm not sure exactly how to chat with my notes, it has never referenced any of my notes.

Do you see any retrieved documents (like in the image) in the Developer Console?
<img width="321" alt="image" src="https://github.com/your-papa/obsidian-Smart2Brain/assets/48623649/b7677daf-fb87-425f-bdf5-a3ee3055d745">

If not you may need to lower the Similarity slider in the toolbar.

**Comment by Leo310** [comment]
> What I wanted from this plugin was to be able to ask things like:
> 
> * "What errors were recorded in the last week?"
> * "Summarize celticos notes"
> * "Summarize my last journal entry"
> * "What positive things did I write about in my journal this year?"

Time-based questions are not possible to answer yet as we currently only use vector similarity search to retrieve the relevant context and no other filtering techniques (for more details [see this video](https://www.youtube.com/watch?v=EYMZVfKcRzM)). 

But the second query "Summarize celticos notes" should work already.
